version: "3.4"
networks:
  notka:
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "6543:1433"
    environment:
      SA_PASSWORD: "admin_123"
      ACCEPT_EULA: "Y"
    networks:
      - notka

  app_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${APPDATA}\ASP.NET\https:/root/.aspnet/https
    build:
      context: .
      dockerfile: NotesAppWeb/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - sql
    networks:
      - notka
