version: "3.4"
networks:
  notka:
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "admin_123"
      ACCEPT_EULA: "Y"
    networks:
      - notka

  app_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5000
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: NotesAppWeb/Dockerfile
    ports:
      - "5000:443"
    depends_on:
      - sql
    command: ["dotnet", "ef", "database update"]
    networks:
      - notka
