version: "3"
networks:
  notka:
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "admin_123"
      ACCEPT_EULA: "Y"
    networks:
      - notka

  app_api:
    build:
      context: .
      dockerfile: NotesAppWeb/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql
    command: ["dotnet", "ef", "database update"]
    networks:
      - notka
